### ISSUE TITLE
Inconsistency in the markdown and JSX file

### ISSUE THREAD

**Issue by molecula451** [ProofSuite/OrFeed#61]
Showing **.secret** as singular

Line 7 <code>truffle-config.js</code> : <code> const mnemonic = readFileSync(".secret").toString().trim(); </code>

On the markdown testing section Step 3:

<code> Create a **.secrets** file in the root folder of this project, and paste into it the mnemonic phrase of the the wallet you </code>

Could be either change on variable or in the markdown

**Comment by mikedeshazer** [comment]
@molecula451  Looking into this

**Comment by mikedeshazer** [comment]
Closing this issue. We'll cover this in release 0.5
