### ISSUE TITLE
Metamask error: Exception thrown in contract code

### ISSUE THREAD

**Issue by landrassy123** [ProofSuite/OrFeed#66]
When attempting to write to my new arbitrage smart contract and call the arb function, I keep getting the above error on metamask regardless of the gas settings. I examined my code and still do not see the issue.

Contract address: https://etherscan.io/address/0x00cf9a57710ce31bb381550e458a59a9034b4051

**Comment by mikedeshazer** [comment]
@landrassy123 make sure to compile with Solidity v. 0.4.26. Should work.

**Comment by landrassy123** [comment]
Unfortunately I have been doing that. Strangely, the example contract from the second yourtube lesson gives the same error - is this simply because I am not the owner or is it the same issue? Or is it possible that come convention(s) has changed since the video and some of my syntax is incorrect? Still having no luck troubleshooting this. Thanks for the prompt reply!

**Comment by landrassy123** [comment]
Could you try to run the tutorial file again and see if you run into the same error - it seems ive tried everything to no avail :(

**Comment by mikedeshazer** [comment]
@landrassy123 try the arb function directly through orfeed... might work better for you. Video tutorial: https://www.youtube.com/watch?v=dFwZvxW3Upw
Was created to simplify things!
