### ISSUE TITLE
Issue executing trades.  Trades get reverted

### ISSUE THREAD

**Issue by tycooperaow** [ProofSuite/OrFeed#67]
So my smart contract has difficulty executing trades and I was able to pinpoint the source of the problem here. 

![chrome_2020-04-10_23-25-48](https://user-images.githubusercontent.com/35544142/79051147-8ca7be80-7bfc-11ea-85f9-bbe669ae4f19.png)

In my terminal, I get this message after the trade has been made. 
![error-with-revert](https://user-images.githubusercontent.com/35544142/79051154-97faea00-7bfc-11ea-9598-a4b88c1ca463.png)

The transactions also get reverted as well, as displayed in the contract transaction
[Contract Address](https://etherscan.io/address/0x1a5924bed24b4dece2b2c217049a7cb6628c1200)

The source of the issues seems to derive from this function in the smart contract:
![chrome_2020-04-10_23-26-55](https://user-images.githubusercontent.com/35544142/79051209-f2944600-7bfc-11ea-9103-af4dface4ce8.png)

They happen once this function is called in the node application:
![issuewithrevert-nodeappsource](https://user-images.githubusercontent.com/35544142/79051316-8ebe4d00-7bfd-11ea-8705-e57e9c9f88d1.png)

**Comment by mikedeshazer** [comment]
@tycooperaow if you verify your contract code on Etherscan, we can debug the error on tenderly.dev and see what's going on. Let me know!

**Comment by tycooperaow** [comment]
How do I go about getting it confirmed on etherscan? I been having some issues with that.

**Comment by mikedeshazer** [comment]
The key is to make sure you select the proper compiler (0.4.26), single file, and set optimized to false (default).
https://etherscan.io/verifyContract?a=0x1a5924bed24b4dece2b2c217049a7cb6628c1200 for your contract

**Comment by tycooperaow** [comment]
I was given this error:

 Error! Unable to generate Contract ByteCode and ABI

**Comment by tycooperaow** [comment]
![chrome_2020-05-04_20-35-57](https://user-images.githubusercontent.com/35544142/81026085-ed669780-8e46-11ea-9bc6-dd69c3865380.png)
`

**Comment by mikedeshazer** [comment]
@tycooperaow you don't need to paste your ABI on Etherscan when doing single files  on compile 0.4.26. Not sure why this is the case on Etherscan but try verifying it without the ABI. Ran into that issue a while back, and just removed the ABI... It's an Etherscan thing...let me know!

**Comment by tycooperaow** [comment]
So I did what you told me and still go the error, here's my process


![chrome_2020-05-10_09-14-49](https://user-images.githubusercontent.com/35544142/81500257-0df77d00-929f-11ea-9f1c-00cf5939e8e2.png)
![chrome_2020-05-10_09-15-56](https://user-images.githubusercontent.com/35544142/81500258-0df77d00-929f-11ea-9db4-0cc7d2501f07.png)
![chrome_2020-05-10_09-16-14](https://user-images.githubusercontent.com/35544142/81500259-0df77d00-929f-11ea-8465-8bd65d286f5c.png)

**Comment by mikedeshazer** [comment]
@tycooperaow the only thing I can think of is the the contract code is indeed not what was submitted. Good news though, a UI for executing arb is coming to OrFeed in the coming days, so will be much easier to test out, figure out where bugs reside (if they reside)!

**Comment by tycooperaow** [comment]
That's good to hear, any update on when it'll be released?

**Comment by mikedeshazer** [comment]
Likely within 72 hours!

**Comment by mikedeshazer** [comment]
@tycooperaow its here https://www.orfeed.org/angle
