### ISSUE TITLE
traderExampleLesson2.sol orfeed.getExchangeRate for Kyber exchange always returns zero

### ISSUE THREAD

**Issue by olegmitrakhovich** [ProofSuite/OrFeed#76]
I've been trying to test out traderExampleLesson2.sol and I noticed that 

`function getKyberBuyPrice() constant returns (uint256){  //change this to SAI
       uint256 currentPrice =  orfeed.getExchangeRate("ETH", "SAI", "BUY-KYBER-EXCHANGE", 1000000000000000000);
        return currentPrice;
    }`

Probably will not work once the contract is deployed. It always returns zero when that function is tried on etherscan when the parameters applied:
https://etherscan.io/address/0x8316b082621cfedab95bf4a44a1d4b64a6ffc336#readContract

Is something wrong with orfeed contract?

(when requesting price from uniswap that works fine)

**Comment by Vamsee30** [comment]
The ether address Mike put is '0x00eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee'

This is wrong, it should be:
'0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee'

Second, the DAI address should be 0x6b175474e89094c44da98b954eedeac495271d0f
