### ISSUE TITLE
Not Retrieving Kyber SAI Sell price 

### ISSUE THREAD

**Issue by kennisnutz** [ProofSuite/OrFeed#77]
I cloned and ran this application but it returned 0 for the value of the Kyber SAI Sell price.

**Comment by mikedeshazer** [comment]
@kennisnutz Kyber no longer supports SAI from my understanding

**Comment by edd34** [comment]
I confirm, SAI is not present in list of token in Kyberswap app.
See below :
https://www.kyberswap.com/swap/eth-knc

@mikedeshazer I think the issue can be closed.

**Comment by kennisnutz** [comment]
thanks for the clarification
